adding java script file for baverage page
GSG-CF05/Foodster-Team04 pull request #37
Opened 2022-03-22 14:01 UTC by bayan2002

relates #36

2022-03-22 14:06 UTC, hamadafarj submitted a review, later dismissed

2022-03-22 14:07 UTC, shathakh submitted a review, later dismissed

2022-03-22 14:15 UTC, sara219 requested changes

2022-03-22 14:15 UTC, sara219 commented on beverage-recipes/beverage-recipes.js
> +      li.appendChild(categoriesBtn);
category tabs need to be a little bigger to be suitable with the category size that's coming from API

<img width="672" alt="Screen Shot 2022-03-22 at 4 13 06 PM" src="https://user-images.githubusercontent.com/47992412/159501595-b878acad-b60f-414a-a365-399f85019e62.png">


set the width to 10.5rem instead of 6.5rem

<img width="672" alt="Screen Shot 2022-03-22 at 4 13 00 PM" src="https://user-images.githubusercontent.com/47992412/159501872-40d1b33e-25d9-453b-b080-c0be68dd4ecc.png">

2022-03-22 17:51 UTC, sara219 approved these changes, later dismissed
💯

2022-03-22 18:29 UTC, hamadafarj approved these changes

2022-03-22 18:50 UTC, hamadafarj commented on beverage-recipes/beverage-recipes.js
> +
Add a new function to save in local storage the drinks
To let abdulqader know form what page the user come

2022-03-22 18:51 UTC, hamadafarj commented on beverage-recipes/beverage-recipes.js
> +
Add a new function to save in local storage the drinks
To let abdulqader know form what page the user come

2022-03-22 18:52 UTC, hamadafarj requested changes
Add a new function to save in local storage the drinks
To let abdulqader know form what page the user come

2022-03-23 07:59 UTC, sara219 approved these changes

2022-03-23 08:51 UTC, hamadafarj approved these changes

2022-03-23 08:55 UTC, AjShatalii approved these changes

2022-03-23 13:21 UTC, merged