linked the API with the foodDB API
GSG-CF05/Foodster-Team04 pull request #38
Opened 2022-03-22 16:36 UTC by AjShatalii

#31

2022-03-22 17:27 UTC, sara219 requested changes

2022-03-22 17:27 UTC, sara219 commented on recipe-page/recipe-page.js
> +    <h4 class="notice">Click on the picture for an illustrative video</h4>`; //Youtube Video
using innerHTML is considered a bad practice, therefore, it is not recommended to use it

use createElement to create a new element ( image, a, h4) and use appendChild to append the element with the parent element

2022-03-23 16:22 UTC, shathakh approved these changes

2022-03-23 16:32 UTC, bayan2002 approved these changes

2022-03-23 16:45 UTC, sara219 approved these changes
💯

2022-03-23 16:46 UTC, merged